import { HealthProfile, FoodProduct, AlternativeProduct, DiningOutDish, ConsultationRequest } from "@/types";

export const DEFAULT_PATIENT_PROFILE: HealthProfile = {
  id: "cds-ananya-rao",
  name: "Ananya Rao",
  patientId: "CDS-8842",
  age: 38,
  gender: "Female",
  conditions: [
    {
      id: "diabetes_type_2",
      label: "Diabetes (Type 2)",
      status: "active",
      criticality: "high",
    },
    {
      id: "hypertension",
      label: "Stage 1 Hypertension",
      status: "active",
      criticality: "medium",
    },
  ],
  thresholds: {
    maxGlycemicLoadPerServing: 10,
    maxSodiumMgPerServing: 400,
    dailySodiumMgCeiling: 1500,
    maxAddedSugarGrams: 0,
    prohibitedSweeteners: ["maltitol", "sorbitol", "isomalt", "hydrogenated starch"],
    prohibitedAllergens: ["peanut"],
  },
  notes: "Requires blunted postprandial glucose excursions and low sodium density to stabilize blood pressure.",
  updatedAt: new Date().toISOString(),
};

export const BENCHMARK_SCANNED_FOODS: Record<string, FoodProduct> = {
  "nutrichoice-digestive": {
    id: "nutrichoice-digestive",
    name: "NutriChoice Sugar-Free Digestive",
    brand: "Britannia",
    category: "Packaged biscuit",
    batchNumber: "#9042",
    barcode: "8901063012948",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDBZptGqTJjIhAXLtDZt25_dGFyTc4lla-ianavu_Ic6joTcR_Io91AyZJX0naQd3hQWOk9gJUrhWp1DYaBYmRUn3FEjBE0sh1MwKgoHqAYWhpoNeSmkIqj9ozuaQfihskH3GWxTN1OJh-6ymzKRUKMlKcy83Tfb9USOvBYXzYA5Ar8OH9Vhhl3JVn6GYKewly3EUfMqMM1wS2Ig8MAAn0pW_IJjfRafxtQYaetpEZ4J4FmCqEdGpM",
    confidenceScore: 98.4,
    scannedAt: new Date(Date.now() - 120000).toISOString(),
    overallStatus: "flagged",
    hiddenPolyolsDetected: 4.8,
    nutrition: {
      servingSize: "2 biscuits (25g)",
      servingsPerContainer: 8,
      calories: 118,
      totalCarbohydratesGrams: 18.2,
      dietaryFiberGrams: 1.5,
      totalSugarsGrams: 0.4,
      addedSugarsGrams: 0,
      sugarAlcoholsPolyolsGrams: 4.8, // Maltitol
      netCarbohydratesGrams: 16.7,
      proteinGrams: 2.1,
      totalFatGrams: 4.8,
      saturatedFatGrams: 2.2,
      sodiumMg: 145,
      glycemicLoadScore: 14.2, // High for a single snack portion
    },
    ingredients: [
      {
        id: "ing-1",
        name: "Refined Wheat Flour (Maida - 56.4%)",
        declaredOrder: 1,
        percentageEstimate: 56.4,
        category: "starch_flour",
        glycemicImpact: "high",
        riskSeverity: "high",
        clinicalNote: "Rapidly converted into simple glucose. Carries high glycemic index (GI 85).",
      },
      {
        id: "ing-2",
        name: "Polyols / Maltitol Syrup (965[ii])",
        declaredOrder: 2,
        category: "sweetener",
        glycemicImpact: "medium",
        isPolyolOrArtificialSweetener: true,
        riskSeverity: "high",
        eNumber: "INS 965(ii)",
        clinicalNote: "Carries 50% relative glycemic response of table sugar despite zero sugar label claims.",
      },
      {
        id: "ing-3",
        name: "Refined Palm Oil",
        declaredOrder: 3,
        category: "fat_oil",
        glycemicImpact: "low",
        riskSeverity: "moderate",
        clinicalNote: "High saturated palmitic fatty acids.",
      },
      {
        id: "ing-4",
        name: "Wheat Bran (4.5%)",
        declaredOrder: 4,
        percentageEstimate: 4.5,
        category: "whole_food",
        glycemicImpact: "low",
        riskSeverity: "low",
        clinicalNote: "Insoluble dietary fiber.",
      },
      {
        id: "ing-5",
        name: "Raising Agents (INS 500[ii], INS 503[ii])",
        declaredOrder: 5,
        category: "additive",
        glycemicImpact: "low",
        riskSeverity: "low",
        eNumber: "INS 500(ii)",
        clinicalNote: "Sodium bicarbonate and ammonium bicarbonate leavening agents.",
      },
      {
        id: "ing-6",
        name: "Iodised Salt (0.6%)",
        declaredOrder: 6,
        percentageEstimate: 0.6,
        category: "additive",
        glycemicImpact: "low",
        riskSeverity: "low",
        clinicalNote: "Within safe allowance for single portion.",
      },
    ],
    clinicalFlags: [
      {
        id: "flag-refined-carbs",
        title: "Refined carbohydrates",
        severity: "high",
        affectedCondition: "diabetes_type_2",
        rationale: "Listed as 1st ingredient by volume (>55% composition weight).",
        threeStepChain: {
          profileStep: "Personal insulin sensitivity index requires low glycemic load.",
          foodInfoStep: "Refined wheat flour listed prominently as 1st ingredient by volume (>55% composition weight).",
          potentialRelevanceStep: "Rapid starch conversion may cause significant postprandial glucose elevation despite zero added table sugar.",
        },
      },
      {
        id: "flag-added-sweeteners",
        title: "Added sweeteners (Maltitol)",
        severity: "moderate",
        affectedCondition: "diabetes_type_2",
        rationale: "Polyol maltitol syrup creates non-zero glycemic excursions.",
        threeStepChain: {
          profileStep: "Active diabetes baseline monitors polyol sugar alcohols with GI > 20.",
          foodInfoStep: "Contains Maltitol Syrup (INS 965ii) with glycemic index between 35 and 52.",
          potentialRelevanceStep: "May elevate blood sugar levels 45-75 minutes after consumption.",
        },
      },
      {
        id: "flag-sodium",
        title: "Sodium Content",
        severity: "low",
        affectedCondition: "hypertension",
        rationale: "145mg sodium is compliant with your single-snack threshold of <400mg.",
        threeStepChain: {
          profileStep: "Hypertension profile monitors sodium density.",
          foodInfoStep: "145mg per 25g serving.",
          potentialRelevanceStep: "Compliant with single-snack safety thresholds.",
        },
      },
    ],
  },
  "instant-noodles": {
    id: "instant-noodles",
    name: "Classic Instant Masala Noodles",
    brand: "Maggi",
    category: "Packaged noodles",
    batchNumber: "#4102",
    barcode: "8901058852337",
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=600&auto=format&fit=crop&q=80",
    confidenceScore: 97.2,
    scannedAt: new Date(Date.now() - 7200000).toISOString(),
    overallStatus: "flagged",
    hiddenPolyolsDetected: 0,
    nutrition: {
      servingSize: "1 pack (70g)",
      servingsPerContainer: 1,
      calories: 310,
      totalCarbohydratesGrams: 42.0,
      dietaryFiberGrams: 2.1,
      totalSugarsGrams: 2.2,
      addedSugarsGrams: 1.0,
      sugarAlcoholsPolyolsGrams: 0,
      netCarbohydratesGrams: 39.9,
      proteinGrams: 6.5,
      totalFatGrams: 13.0,
      saturatedFatGrams: 6.2,
      sodiumMg: 840, // High Sodium Flag
      glycemicLoadScore: 28.5,
    },
    ingredients: [
      {
        id: "noodles-ing-1",
        name: "Refined Wheat Flour (Maida)",
        declaredOrder: 1,
        category: "starch_flour",
        glycemicImpact: "high",
        riskSeverity: "high",
        clinicalNote: "High GI refined carbohydrate base.",
      },
      {
        id: "noodles-ing-2",
        name: "Palm Oil",
        declaredOrder: 2,
        category: "fat_oil",
        glycemicImpact: "low",
        riskSeverity: "moderate",
      },
      {
        id: "noodles-ing-3",
        name: "Iodised Salt & Flavor Enhancers (635)",
        declaredOrder: 3,
        category: "additive",
        glycemicImpact: "low",
        riskSeverity: "high",
        clinicalNote: "High sodium concentration (840mg per serving).",
      },
    ],
    clinicalFlags: [
      {
        id: "flag-noodles-sodium",
        title: "High sodium (840mg / serve)",
        severity: "high",
        affectedCondition: "hypertension",
        rationale: "Exceeds recommended per-meal sodium allowance of 400mg by more than 110%.",
        threeStepChain: {
          profileStep: "Hypertension profile restricts single meal sodium to <400mg.",
          foodInfoStep: "Declared sodium is 840mg per single pack.",
          potentialRelevanceStep: "Directly correlates with arterial fluid retention and systolic pressure spikes.",
        },
      },
    ],
  },
  "peanut-chikki": {
    id: "peanut-chikki",
    name: "Traditional Peanut & Jaggery Chikki",
    brand: "Heritage Sweets",
    category: "Indian confectionery",
    batchNumber: "#CH-11",
    barcode: "8902049102441",
    imageUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600&auto=format&fit=crop&q=80",
    confidenceScore: 99.1,
    scannedAt: new Date(Date.now() - 86400000).toISOString(),
    overallStatus: "flagged",
    hiddenPolyolsDetected: 0,
    nutrition: {
      servingSize: "1 bar (40g)",
      calories: 215,
      totalCarbohydratesGrams: 24.0,
      dietaryFiberGrams: 1.8,
      totalSugarsGrams: 16.5,
      addedSugarsGrams: 16.5,
      sugarAlcoholsPolyolsGrams: 0,
      netCarbohydratesGrams: 22.2,
      proteinGrams: 5.5,
      totalFatGrams: 11.0,
      saturatedFatGrams: 2.1,
      sodiumMg: 28,
      glycemicLoadScore: 18.0,
    },
    ingredients: [
      {
        id: "chikki-ing-1",
        name: "Roasted Peanuts (Arachis hypogaea - 52%)",
        declaredOrder: 1,
        category: "whole_food",
        glycemicImpact: "low",
        riskSeverity: "critical",
        clinicalNote: "Severe allergenic storage protein (Ara h 1, Ara h 2).",
      },
      {
        id: "chikki-ing-2",
        name: "Jaggery (Cane Molasses)",
        declaredOrder: 2,
        category: "sweetener",
        glycemicImpact: "high",
        riskSeverity: "high",
        clinicalNote: "Unrefined sugar with high rapid sucrose content.",
      },
    ],
    clinicalFlags: [
      {
        id: "flag-allergen-peanut",
        title: "Allergen detected · Peanut",
        severity: "critical",
        affectedCondition: "peanut_allergy",
        rationale: "Patient has documented severe peanut sensitivity. Strictly avoid.",
        threeStepChain: {
          profileStep: "Active allergy safety profile flags peanut proteins.",
          foodInfoStep: "Contains 52% whole roasted peanuts.",
          potentialRelevanceStep: "Risk of acute immunological reaction.",
        },
      },
    ],
  },
};

export const SAFER_ALTERNATIVES: AlternativeProduct[] = [
  {
    id: "alt-true-elements",
    name: "True Elements Rolled Oats Crackers",
    brand: "True Elements",
    code: "TE-782",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAQ7-8urb0dBM_QwJ_RnDX5Ssz2WxsQ9E9RZP-Q3lT3TNQ0R1m6Oo6FnJrYJPaNVhfBoAB04mZmpysbmXijdfq20oDs3lr1v5ky_lqpsCl9ZWs3vwr_oMpHI4ZWFvBwyFsAzj9POvKJV1HVgYWVdoQsPGCo-cHMXnubXXNVHOqigBUmcEEx6SfBp7UUmg0eCOxKshKDwuHo1TEjJnd3Lfh_plC5xQifizAE4V_zZXCPbDP7F8BHUfY",
    compatibilityPercentage: 94,
    netCarbsGrams: 8.2,
    glycemicCategory: "Low Glycemic",
    glycemicLoad: 4.1,
    addedSweetenersGrams: 0,
    sweetenerNote: "Stevia leaf / Zero maltitol",
    sodiumMg: 95,
    sodiumNote: "Low sodium density",
    clinicalRationale: "Lower glycemic impact · Whole grain complex carbs · No artificial polyols or maltitol.",
    fiberDensity: "3.4g/srv",
    detailsSummary: "Verified zero maltodextrin additives through multi-stage chromatographic panel analysis.",
  },
  {
    id: "alt-the-whole-truth",
    name: "The Whole Truth Multigrain Crispbread",
    brand: "The Whole Truth",
    code: "TWT-409",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAdvMABNXQjIfiEZUPCjMQ1QnRY4I0zZ3OecqPtcYZHN2oD-sWv4rW5icOTdXc_RxFNRfywPmYTp9EMpc1g8ljjYVFwKvJdjAT5DxFRxXmjV4LfTUUDJkp56IfpKniwIEtPjQuF9BKCoxr2WQQExdA6xwZwScFR76F7toTb1Vf5yyMTN0PMTOCAJxiUz6YRrQEMMkdWUH5SaUo0aYN6_UCAJBdOj-Cy0yzFi3t4GnZKpecDk8JEGiQ",
    compatibilityPercentage: 89,
    netCarbsGrams: 11.0,
    glycemicCategory: "Low Glycemic",
    glycemicLoad: 5.6,
    addedSweetenersGrams: 0,
    sweetenerNote: "100% compliant",
    sodiumMg: 140,
    sodiumNote: "Within safety threshold",
    clinicalRationale: "100% declared ingredients · Zero hidden maltodextrin or refined maida.",
    fiberDensity: "4.2g/srv",
    detailsSummary: "Certified unrefined whole grain formulation completely eliminating post-prandial reactive spikes.",
  },
  {
    id: "alt-diabetic-chef",
    name: "A Diabetic Chef Roasted Seed Thins",
    brand: "A Diabetic Chef",
    code: "ADC-114",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDuIiMCKkNkVI7uQN0PiASYfSHB4HsZpLVSvXBBKBw10o_F4PqkR2_yAaqxf4RPQrFJpN5DkvbDMMzuxMFyNttLnvPiwUNXV6RTMDcp-Hdj0kEvwF6zRU1SOLvQ4QQH5fEKnbVArrtj2jY04T_sA1I2snmUkHhiydhXUOSC58lK4ESAkpUUNNkr5V-EztbRDP6ULgL1bfFgmzK3xAKuZFcmvg8uPNuooxRNrkjrHicsW4HUgEqwIJs",
    compatibilityPercentage: 96,
    netCarbsGrams: 4.5,
    glycemicCategory: "Very Low Glycemic",
    glycemicLoad: 1.8,
    addedSweetenersGrams: 0,
    sweetenerNote: "Zero chemical sweeteners",
    sodiumMg: 160,
    sodiumNote: "Hypertension compliant",
    clinicalRationale: "High dietary fiber (6.8g) blunts glucose spike · Keto & diabetic friendly.",
    fiberDensity: "6.8g/srv",
    detailsSummary: "Clinical compound assay reveals significant soluble mucilage that attenuates carbohydrate breakdown kinetics.",
  },
];

export const DINING_OUT_SAMPLE_DISHES: DiningOutDish[] = [
  {
    id: "paneer-tikka",
    dishName: "Paneer Tikka (Tandoori Dry)",
    venueType: "Restaurant",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAhebP4UEzPFxQikKmR2tcufScbO1IVrDdZxLBsNYf5E4fSGdk3aKqJf323hfBug7yRCLgRaYF2Y7wy5TYpQPw3J5giUIXoJ7ooRbykgEMpTGJkLBqkcyd1BvH_aR46Ua6avu3gd2TasdbyomoN8NrPumAO6viEcLuOp9BCa9ULMR8sDEYZNhZ3Dm3whQwKvz-SzU-Iv2PZW3vSYzRbzGsD1QKqPfOdp_N0hI9pB8MnCcAUYsWRq28",
    estimatedCalories: 320,
    confidenceLevel: "Partial",
    uncertaintyDescription: "Prepared food without standardized packaging. Ingredients inferred from typical culinary preparation standards.",
    concerns: [
      {
        title: "Sodium Content",
        level: "moderate",
        description: "Tandoori marinades frequently rely on black salt and chaat masala, driving sodium to ~520mg per serving.",
      },
      {
        title: "Carbohydrate & Sugar",
        level: "low",
        description: "Dry paneer is naturally low carb (~4g) with high protein & calcium, minimal glycemic response.",
      },
      {
        title: "Cooking Fat & Dairy",
        level: "moderate",
        description: "Check for heavy melted butter brushing prior to serving if monitoring saturated fats.",
      },
    ],
    customizationTips: [
      "Ask the server: 'Please do not brush melted butter before serving.'",
      "Request: 'Sprinkle light lemon juice instead of extra chaat masala salt.'",
      "Pair with fresh mint chutney made without added table sugar.",
    ],
  },
  {
    id: "dal-tadka",
    dishName: "Yellow Dal Tadka with Steamed Rice",
    venueType: "Restaurant",
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80",
    estimatedCalories: 380,
    confidenceLevel: "Partial",
    uncertaintyDescription: "Steamed polished white rice contributes a fast glycemic index load.",
    concerns: [
      {
        title: "Glycemic Index of White Rice",
        level: "high",
        description: "Polished basmati or sonamasuri rice has a GI of 72, which may induce rapid blood glucose elevation.",
      },
      {
        title: "Added Ghee / Tempering",
        level: "moderate",
        description: "Double tadka increases lipid density; request single light olive oil or cumin-only tadka.",
      },
    ],
    customizationTips: [
      "Ask to substitute polished white rice with brown rice, quinoa, or whole wheat roti.",
      "Request: 'Light tadka with minimum oil and no extra table salt.'",
    ],
  },
];

export const CLINICAL_TRENDS_MOCK = [
  { day: "Mon", glycemicLoad: 8.2, sodiumMg: 310, safeCount: 4, flaggedCount: 0 },
  { day: "Tue", glycemicLoad: 9.4, sodiumMg: 380, safeCount: 3, flaggedCount: 1 },
  { day: "Wed", glycemicLoad: 7.1, sodiumMg: 290, safeCount: 5, flaggedCount: 0 },
  { day: "Thu", glycemicLoad: 14.2, sodiumMg: 840, safeCount: 2, flaggedCount: 2 },
  { day: "Fri", glycemicLoad: 6.8, sodiumMg: 270, safeCount: 6, flaggedCount: 0 },
  { day: "Sat", glycemicLoad: 11.0, sodiumMg: 420, safeCount: 4, flaggedCount: 1 },
  { day: "Sun", glycemicLoad: 5.5, sodiumMg: 240, safeCount: 5, flaggedCount: 0 },
];

export const DOCTOR_PATIENTS = [
  {
    id: "ananya-rao",
    name: "Ananya Rao",
    patientId: "CDS-8842",
    age: 38,
    gender: "Female",
    conditions: ["Diabetes (Type 2)", "Stage 1 Hypertension", "Peanut Allergy"],
    riskLevel: "high" as const,
    lastEvaluated: "12 mins ago",
    todayIntake: {
      sodiumMg: 620,
      glycemicLoadAvg: 14.2,
      flagsCount: 3,
    },
  },
  {
    id: "rajesh-kumar",
    name: "Rajesh Kumar",
    patientId: "CDS-4019",
    age: 52,
    gender: "Male",
    conditions: ["Stage 2 Hypertension", "Hyperlipidemia"],
    riskLevel: "high" as const,
    lastEvaluated: "2 hours ago",
    todayIntake: {
      sodiumMg: 1150,
      glycemicLoadAvg: 8.5,
      flagsCount: 2,
    },
  },
  {
    id: "priya-sharma",
    name: "Priya Sharma",
    patientId: "CDS-6621",
    age: 29,
    gender: "Female",
    conditions: ["Celiac Disease", "Lactose Sensitivity"],
    riskLevel: "moderate" as const,
    lastEvaluated: "Yesterday",
    todayIntake: {
      sodiumMg: 380,
      glycemicLoadAvg: 6.1,
      flagsCount: 1,
    },
  },
];

export const DOCTOR_ASSESSMENTS_TABLE = [
  {
    id: "nutrichoice",
    foodName: "NutriChoice Sugar-Free",
    brand: "Britannia · Packaged Cracker",
    category: "Biscuit",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBvIvy79bCQ4g0Ulj4D33-r-dX3h13-gzoZL7mvucWJQLija4f7PYW_YLndL81nQwcUKc00PmYX5JYNPB_llzSIZsrgWgy5W38BVAk2yJR60MA-0V5msmAGPlks1KYdBPBpxtbJJlra6UHS-V-3obLTDpNkYQZGNTlh79NNE3OXMsa7jxbReS4wGs90lgqpb06mrJO2od8lWd4GFept5lzYE06X4eriVB7oVanUEAERdSedVu7grE4",
    detectedDate: "Today, 11:20 AM",
    riskFlag: "Moderate Trigger" as const,
    riskSeverity: "high" as const,
    keyIngredient: "Refined Wheat Flour (Maida 56%)",
    keyIngredientDetail: "Labeled sugar-free; GI is high (~71). Maltitol syrup carries 50% relative glycemic load.",
    infoQuality: "Full OCR (100%)",
    infoQualityScore: 100,
  },
  {
    id: "instant-noodles",
    foodName: "Masala Instant Noodles",
    brand: "Maggi · Quick Meal",
    category: "Noodles",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCwh1JTf4ksTV5hXziqVU22ya8Yz6sWS9_X_B1iWPLc7LEIbCpSPQw-Ht4KPGcQDAN2QiHPVuDCllbkrZSGXXvMDaxw173tZYot9-Qx7sSZugcsTK1NGFUJmWkmzAP2Z32PdQhfSuJ25QAl_aCru3SZfOEEvmZ_IBmrG5Unj4sVnAxn46_p9-pvomgm4NygfaOBP1u2EvK-CCQMXaFHA9W3uWMrMcJa-wb9ktoO_uvp88DoZs1qBpQ",
    detectedDate: "Yesterday, 19:45",
    riskFlag: "High Hazard" as const,
    riskSeverity: "critical" as const,
    keyIngredient: "840mg Sodium / serving",
    keyIngredientDetail: "56% of patient daily ceiling (1,500mg). Saturated palm fats.",
    infoQuality: "Lab-Verified (98%)",
    infoQualityScore: 98,
  },
  {
    id: "paneer-tikka",
    foodName: "Paneer Tikka (Tandoori)",
    brand: "Pind Balluchi · Dining Out",
    category: "Restaurant",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCOdCX3lCRZwCJMslWvAbgd2PliP3Cc86lVCUGwLl5MCNLGxvwnqZfie7ovK5g1U8Y5wQdtweoQd_yFtStW-xp4-a9vhvn7EWiGRvYBubb528hlhM9O3I-oqpCtjt4iBhKxlOIgdgqBo_7LMw3bvnR6WHtRzpAbravlACxb2hdsbEjHmrvScy2KLAef5g-Tc31AkQLyz-RiTE-BzZ6BGrfGxAyAtbcEHPCGzozhwak-La8kNfZBccU",
    detectedDate: "Oct 21, 2024",
    riskFlag: "Partial Alert" as const,
    riskSeverity: "moderate" as const,
    keyIngredient: "Tandoori Red Color & Brine",
    keyIngredientDetail: "Possible added salt brine; oil unknown. Recommend unbrushed butter.",
    infoQuality: "Partial Menu Data",
    infoQualityScore: 72,
  },
  {
    id: "greek-yogurt",
    foodName: "Plain Greek Yogurt 0%",
    brand: "Epigamia · Dairy Refrigerated",
    category: "Dairy",
    imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDLQOD9OY0-a9CYXEJadF_DXH9HzSIKIqbEhJRwB_InTkxbuGA_Oso_LdBC3daI9Fz6pQG-hGL8W2scpTV6UHGSoi7H_wKqJRTxO2pn2xiq4MHj1rYdHEa8u9dahsxnnSBW27EDMRbCkyJWIHOAICSJc_t4Q3rCrqWSApkBSO2wiMNubhGVUMKKfWXy9ysp9Wbe27YMcE4wO1QKGRvJtdRbbjzhnU_uwLqlH8E-wFzvcgh17elpnAE",
    detectedDate: "Oct 20, 2024",
    riskFlag: "Low Risk / Safe" as const,
    riskSeverity: "low" as const,
    keyIngredient: "Pasteurized Milk + Live Cultures",
    keyIngredientDetail: "Zero added sucrose, Na: 45mg. High protein blunts glycemic response.",
    infoQuality: "Lab-Verified (100%)",
    infoQualityScore: 100,
  },
];

export const DEMO_CONSULTATION_REQUESTS: ConsultationRequest[] = [
  {
    id: "consult-ananya-pizza",
    patientName: "Ananya Rao",
    patientId: "CDS-8842",
    patientAge: 38,
    patientGender: "Female",
    conditions: ["Diabetes (Type 2)", "Stage 1 Hypertension"],
    foodName: "Pepperoni Pizza",
    brand: "Generic · Pizza",
    category: "Fast Food",
    imageUrl: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=500&auto=format&fit=crop&q=80",
    triageScore: 97,
    overallStatus: "flagged",
    clinicalFlags: [
      {
        id: "flag-1",
        title: "Refined carbohydrates listed prominently",
        severity: "high",
        affectedCondition: "diabetes_type_2",
        rationale: "Rapid starch conversion precipitates acute postprandial glycemic excursions.",
        threeStepChain: {
          profileStep: "Personal insulin sensitivity requires low glycemic load.",
          foodInfoStep: "Refined wheat crust is primary ingredient by mass.",
          potentialRelevanceStep: "Causes postprandial glucose spike beyond 180 mg/dL target.",
        },
      },
      {
        id: "flag-2",
        title: "Glycemic Load (23) exceeds meal limit (10)",
        severity: "high",
        affectedCondition: "diabetes_type_2",
        rationale: "33g carbs with fast enzymatic absorption exceeds customized target.",
        threeStepChain: {
          profileStep: "Meal GL ceiling is 10.",
          foodInfoStep: "Calculated slice GL is 23.",
          potentialRelevanceStep: "Prolongs glucose elevation window.",
        },
      },
      {
        id: "flag-3",
        title: "Sodium Spike (650mg / slice)",
        severity: "high",
        affectedCondition: "hypertension",
        rationale: "Single portion exceeds clinical ceiling of 400mg.",
        threeStepChain: {
          profileStep: "Stage 1 Hypertension portion ceiling is 400mg.",
          foodInfoStep: "Measured sodium is 650mg.",
          potentialRelevanceStep: "May precipitate blood pressure elevation.",
        },
      },
    ],
    nutrition: {
      servingSize: "1 Slice (1/8 of 14-inch)",
      calories: 285,
      totalCarbohydratesGrams: 33,
      netCarbohydratesGrams: 30.5,
      dietaryFiberGrams: 2.5,
      totalSugarsGrams: 4,
      addedSugarsGrams: 1,
      sugarAlcoholsPolyolsGrams: 0,
      proteinGrams: 14,
      totalFatGrams: 12,
      saturatedFatGrams: 4.5,
      sodiumMg: 650,
      glycemicLoadScore: 23,
    },
    patientNote: "I'm having dinner with family and wanted to check if 1 slice of this pepperoni pizza is okay with my medication regimen.",
    requestedAt: "Just now (Live)",
    status: "pending",
    roomId: "cds-room-ananya-8842",
  },
  {
    id: "consult-rajesh-snack",
    patientName: "Rajesh Kumar",
    patientId: "CDS-4019",
    patientAge: 52,
    patientGender: "Male",
    conditions: ["Stage 2 Hypertension", "Hyperlipidemia"],
    foodName: "Masala Instant Noodles",
    brand: "Maggi · Quick Meal",
    category: "Packaged Noodles",
    imageUrl: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=500&auto=format&fit=crop&q=80",
    triageScore: 88,
    overallStatus: "flagged",
    clinicalFlags: [
      {
        id: "flag-sodium",
        title: "Critical Sodium Density (840mg)",
        severity: "critical",
        affectedCondition: "hypertension",
        rationale: "Over 56% of daily sodium quota in a single packaged serving.",
        threeStepChain: {
          profileStep: "Stage 2 Hypertension limit is 400mg per snack.",
          foodInfoStep: "Contains 840mg sodium in single noodle cake.",
          potentialRelevanceStep: "Risk of intravascular fluid overload.",
        },
      },
      {
        id: "flag-palm-fat",
        title: "High Saturated Palm Fat Matrix",
        severity: "high",
        affectedCondition: "hypertension",
        rationale: "Accelerates atherogenic lipid profiles in hyperlipidemia.",
        threeStepChain: {
          profileStep: "Requires minimal atherogenic fat intake.",
          foodInfoStep: "Deep-fried in palm oil.",
          potentialRelevanceStep: "Elevates LDL and arterial stiffness.",
        },
      },
    ],
    nutrition: {
      servingSize: "70g pack",
      calories: 310,
      totalCarbohydratesGrams: 42,
      netCarbohydratesGrams: 40,
      dietaryFiberGrams: 2,
      totalSugarsGrams: 2.1,
      addedSugarsGrams: 0.5,
      sugarAlcoholsPolyolsGrams: 0,
      proteinGrams: 6,
      totalFatGrams: 13,
      saturatedFatGrams: 6,
      sodiumMg: 840,
      glycemicLoadScore: 28,
    },
    patientNote: "Need quick lunch at work. Want to know if discarding the tastemaker packet makes it safe for my blood pressure.",
    requestedAt: "18 mins ago",
    status: "pending",
    roomId: "cds-room-rajesh-4019",
  },
  {
    id: "consult-priya-biscuit",
    patientName: "Priya Sharma",
    patientId: "CDS-6621",
    patientAge: 29,
    patientGender: "Female",
    conditions: ["Diabetes (Type 2)", "PCOS"],
    foodName: "Digestive High Fibre Biscuits",
    brand: "NutriChoice · Packaged",
    category: "Biscuits & Bakery",
    imageUrl: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=500&auto=format&fit=crop&q=80",
    triageScore: 54,
    overallStatus: "caution",
    clinicalFlags: [
      {
        id: "flag-caution-sugar",
        title: "Maltitol & Polyol Sweetener Load (4.2g)",
        severity: "moderate",
        affectedCondition: "diabetes_type_2",
        rationale: "Hidden sugar alcohol produces delayed glucose elevation.",
        threeStepChain: {
          profileStep: "Insulin timing requires transparency on sugar alcohols.",
          foodInfoStep: "Contains 4.2g maltitol.",
          potentialRelevanceStep: "May produce delayed late-night glucose spike.",
        },
      },
    ],
    nutrition: {
      servingSize: "2 Biscuits (25g)",
      calories: 110,
      totalCarbohydratesGrams: 17,
      netCarbohydratesGrams: 14.9,
      dietaryFiberGrams: 2.1,
      totalSugarsGrams: 3.5,
      addedSugarsGrams: 0,
      sugarAlcoholsPolyolsGrams: 4.2,
      proteinGrams: 2,
      totalFatGrams: 4,
      saturatedFatGrams: 1.5,
      sodiumMg: 120,
      glycemicLoadScore: 9,
    },
    patientNote: "Advertised as diabetes-friendly digestive. Should I substitute with plain roasted almonds?",
    requestedAt: "45 mins ago",
    status: "pending",
    roomId: "cds-room-priya-6621",
  },
];


